openapi: 3.0.1
info:
  title: Oauth_CustomerManagement
  description: ''
  version: '1.0'
servers:
  - url: https://apim-ginr-dev-backend-001.azure-api.net/customer-management-api
paths:

  /customers/create:
    post:
      summary: Crear Cliente
      description: Servicio utilizado para crear el cliente.
      operationId: crear-cliente
      responses:
        '200':
          description: 'null'

  /customers/kpiclientes:
    get:
      summary: kpiclientes
      description: Consulta promedio edad de todos los clientes y desviación estándar entre las edades de todos los clientes
      operationId: kpi-clientes
      responses:
        '200':
          description: ""

  /customers/listclientes:
    get:
      summary: listclientes
      description: Consulta datos de clientes  mas fecha probable de muerte de cada una
      operationId: list-clientes
      responses:
        '200':
          description: ""
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []